### PR TITLE
Solve Cannot declare class SerializationException

### LINKED ISSUE #157: Cannot declare class Amp\Parallel\Sync\SerializationException
With version 1.4.2 https://github.com/amphp/parallel/blob/1.x/lib/Sync/functions.php

When I install (or use) the following set of dependencies:

```
{
  "name": "mikeill/testing",
  "description": "Testing",
  "require": {
      "php": ">=8.0",
      "composer/installers": "2.x",
      "stevegrunwell/wp-cache-remember": "dev-master",
      "micropackage/requirements": "^1.2",
      "wpbp/debug": "dev-master",
      "inpsyde/wp-context": "^1.4",
      "decodelabs/tagged": "^0.14.6",
      "twilio/sdk": "^6.44",
      "vlucas/phpdotenv": "^5.5",
      "inpsyde/assets": "^2.8"
  },
  "require-dev": {
      "dealerdirect/phpcodesniffer-composer-installer": "^0.7",
      "phpro/grumphp": "^1.13",
      "szepeviktor/phpstan-wordpress": "^1.1.2",
      "codeatcode/codeatcs": "^1.0",
      "wp-coding-standards/wpcs": "dev-develop"
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "config": {
    "allow-plugins": {
      "composer/installers": true,
      "dealerdirect/phpcodesniffer-composer-installer": true,
      "phpro/grumphp": true
    }
  }
}
```

It returns the warning:

```
Warning: Cannot declare class Amp\Parallel\Sync\SerializationException, because the name is already in use in /temp/vendor/amphp/parallel/lib/Sync/functions.php
```

Thanks.

### PR DESCRIPTION
**Pull request by MikeiLL**
I hope fixes #157 

Not sure. The warning goes away in my usage.

### CODE REVIEW

**Comment by trowski** [comment]
Likely the warning is disappearing because your change is missing the namespace separator between `__NAMESPACE__` and the string generated from `SerializationException::class`

**Comment by MikeiLL** [comment]
> Likely the warning is disappearing because your change is missing the namespace separator between `__NAMESPACE__` and the string generated from `SerializationException::class`

Thanks. Not sure what it should be. This?

```
\class_alias(SerializerException::class, __NAMESPACE__ . '\\' . SerializationException::class);
```

**Comment by trowski** [comment]
Come to think of it, `__NAMESPACE__ . '\\' . SerializationException::class` will result in the string `"Amp\Parallel\Sync\Amp\Parallel\Sync\SerializationException"`

So it should be `__NAMESPACE__ . '\\SerializationException'`, though that should be identical to `SerializationException::class`

I wonder if it has to do with the class alias? Try changing top of the file to:

```php
<?php

namespace Amp\Parallel\Sync;

// Note removal of import and alias!

if (!\class_exists(SerializationException::class)) {
    // Alias must be defined in an always-loaded file as catch blocks do not trigger the autoloader.
    \class_alias(\Amp\Serialization\SerializationException::class, SerializationException::class);
}
```

**Comment by MikeiLL** [comment]
> ```
> <?php
> 
> namespace Amp\Parallel\Sync;
> 
> // Note removal of import and alias!
> 
> if (!\class_exists(SerializationException::class)) {
>     // Alias must be defined in an always-loaded file as catch blocks do not trigger the autoloader.
>     \class_alias(\Amp\Serialization\SerializationException::class, SerializationException::class);
> }
> ```

Alas. `Warning: Cannot declare class Amp\Parallel\Sync\SerializationException...`

Same with `__NAMESPACE__ . '\\SerializationException'`

**Comment by trowski** [comment]
At this point I think we may have to resort to an error handler that ignores the warning and carries on. This seems to be a bug in PHP, so we'll have to make the best of it.

```php
if (!\class_exists(SerializationException::class)) {
    // Wrap definition in error handler to avoid apparently PHP bug with preloading, see amphp/parallel#159
    set_error_handler(function (): bool { return true; });
    try {
        // Alias must be defined in an always-loaded file as catch blocks do not trigger the autoloader.
        \class_alias(SerializerException::class, SerializationException::class);
    } finally {
        restore_error_handler();
    }
}
```

I think the above will work, can you please give it a try?

**Comment by MikeiLL** [comment]
> I think the above will work, can you please give it a try?

No more warning. I think I updated the PR.

**Comment by MikeiLL** [comment]
Hey there, @trowski  are you able to merge my PR?  Thanks so much and I hope you don't mind the nudge.

**Review by kelunik — APPROVED** [review]

**Comment by kelunik** [comment]
@MikeiLL Thanks for the reminder, missed that you had updated the PR.

**Pull request merged**
